test

diff --git a/.github/workflows/depen-dropdown.yaml b/.github/workflows/depen-dropdown.yaml
--- a/.github/workflows/depen-dropdown.yaml
+++ b/.github/workflows/depen-dropdown.yaml
@@ -54,7 +54,11 @@ jobs:
               esac
               ;;
             *)
-              echo "Invalid webtarget option!" >&2
-              exit 1
-              ;;
+            #   echo "Invalid webtarget option!" >&2
+            #   exit 1
+            #   ;;
           esac
+
+      - name: skipped validate
+        run: |
+            echo "g next"
